# Generated by Django 4.0.1 on 2022-07-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tag_order_customer_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Tanks'), ('Shorts', 'Shorts'), ('Shirts', 'Shirts'), ('Pants', 'Pants'), ('Jewelries', 'Jewelries'), ('Hats', 'Hats'), ('Shoes', 'Shoes'), ('Makeups', 'Makeups')], max_length=200, null=True),
        ),
    ]
